# Generated by Django 3.0.1 on 2020-05-16 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='review',
            new_name='criteria',
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
