# Generated by Django 3.0.1 on 2020-05-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_auto_20200516_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.DateTimeField(verbose_name='date released'),
        ),
    ]
