# Generated by Django 3.0.1 on 2020-05-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_auto_20200516_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.DateField(verbose_name='date released'),
        ),
    ]
