# Generated by Django 3.0.1 on 2020-05-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_auto_20200516_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.DateTimeField(),
        ),
    ]
