# Generated by Django 3.0.1 on 2020-05-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_auto_20200516_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.DateField(),
        ),
    ]
