# Generated by Django 3.0.1 on 2020-05-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_auto_20200516_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='year',
        ),
    ]
